package gui;

import java.beans.PropertyChangeListener;
import java.util.concurrent.TimeUnit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import settings.Config;

/**
 *
 * @author lmessing
 */
public class Settings extends javax.swing.JDialog
{

    private static final Config CONFIG = Config.getInstance();

    /**
     * Creates new form Settings
     *
     * @param parent - the parent
     * @param modal  - will this dialog block the parent?
     */
    public Settings(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabs = new javax.swing.JTabbedPane();
        jPanGeneral = new javax.swing.JPanel();
        jLabGeneral = new javax.swing.JLabel();
        jPanMIDI = new javax.swing.JPanel();
        jLabMIDI = new javax.swing.JLabel();
        jPanMIDI1 = new javax.swing.JPanel();
        jPanOthers = new javax.swing.JPanel();
        jLabOthers = new javax.swing.JLabel();
        jPanButtons = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButRevert = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButAbort = new javax.swing.JButton();
        jButSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jTabs.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createEmptyBorder(2, 5, 2, 5)));
        jTabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabs.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jTabs.setName("Settings"); // NOI18N

        jLabGeneral.setText("General");
        jPanGeneral.add(jLabGeneral);

        jTabs.addTab("General", jPanGeneral);

        jPanMIDI.setLayout(new java.awt.BorderLayout());

        jLabMIDI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabMIDI.setText("MDI");
        jLabMIDI.setPreferredSize(new java.awt.Dimension(19, 20));
        jPanMIDI.add(jLabMIDI, java.awt.BorderLayout.NORTH);

        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.rowHeights = new int[] {30};
        jPanMIDI1.setLayout(jPanel3Layout);
        jPanMIDI.add(jPanMIDI1, java.awt.BorderLayout.CENTER);

        jTabs.addTab("MIDI", jPanMIDI);

        jLabOthers.setText("Others");
        jPanOthers.add(jLabOthers);

        jTabs.addTab("Others", jPanOthers);

        getContentPane().add(jTabs, java.awt.BorderLayout.CENTER);

        jPanButtons.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButRevert.setText("Reset to Default");
        jButRevert.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButRevertActionPerformed(evt);
            }
        });
        jPanel1.add(jButRevert);

        jPanButtons.add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButAbort.setText("Abort");
        jButAbort.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButAbortActionPerformed(evt);
            }
        });
        jPanel2.add(jButAbort);

        jButSave.setText("Save");
        jButSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButSaveActionPerformed(evt);
            }
        });
        jPanel2.add(jButSave);

        jPanButtons.add(jPanel2);

        getContentPane().add(jPanButtons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButSaveActionPerformed
    {//GEN-HEADEREND:event_jButSaveActionPerformed
        buttonSave();
    }//GEN-LAST:event_jButSaveActionPerformed

    private void jButAbortActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButAbortActionPerformed
    {//GEN-HEADEREND:event_jButAbortActionPerformed
        buttonAbort();
    }//GEN-LAST:event_jButAbortActionPerformed

    private void jButRevertActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButRevertActionPerformed
    {//GEN-HEADEREND:event_jButRevertActionPerformed
        buttonRevert();
    }//GEN-LAST:event_jButRevertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                Settings dialog = new Settings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }

                });
                dialog.setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAbort;
    private javax.swing.JButton jButRevert;
    private javax.swing.JButton jButSave;
    private javax.swing.JLabel jLabGeneral;
    private javax.swing.JLabel jLabMIDI;
    private javax.swing.JLabel jLabOthers;
    private javax.swing.JPanel jPanButtons;
    private javax.swing.JPanel jPanGeneral;
    private javax.swing.JPanel jPanMIDI;
    private javax.swing.JPanel jPanMIDI1;
    private javax.swing.JPanel jPanOthers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabs;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setVisible(boolean b)
    {
        setAllComponents();

        setLocationRelativeTo(this.getParent());

        setActivePanel(CONFIG.getActiveConfigPanel());

        super.setVisible(b);
    }

    @Override
    public void dispose()
    {
        buttonAbort();
    }

    public static void setChangeListener(PropertyChangeListener listener)
    {
        CONFIG.setListener(listener);
    }

    /**
     * @brief Sets the active panel. If the index is out of bounds the active index will be set to zero.
     * @param index
     */
    private void setActivePanel(int index)
    {
        try
        {
            jTabs.setSelectedIndex(CONFIG.getActiveConfigPanel());
        }
        catch (IndexOutOfBoundsException ex)
        {
            jTabs.setSelectedIndex(0);
        }
    }

    private void setAllComponents()
    {
        // set values of components from current config
    }

    private void buttonSave()
    {
        System.out.println("Save Settings");
        try
        {
            // store values into CONFIG
        }
        catch (IllegalArgumentException ex)
        {
            JOptionPane.showMessageDialog(this, "Value not supported:\n\n" + ex.getMessage(), "", JOptionPane.ERROR_MESSAGE);
            return; // do not exit window
        }

        CONFIG.save();
        super.dispose();
    }

    private void buttonAbort()
    {
        // only save which config panel is showing
        CONFIG.storeActiveConfigPanel(jTabs.getSelectedIndex(), true);
        CONFIG.save();

        super.dispose();
    }

    private void buttonRevert()
    {
        String options[] =
        {
            "Yes", "No", "Oh shit!"
        };
        JLabel message = new JLabel("<html><body><div width='200px' align='center'>This will revert all settings to the default values!<br><br>Are you sure?<br><br></div><body></html>", JLabel.CENTER);
        int response = JOptionPane.showOptionDialog(this, message, "Revert Settings?", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[1]);

        if(response == 0)
        {
            CONFIG.revertSettings();
            CONFIG.save();

            setAllComponents();
        }

        // easter egg
        if(response == 2)
        {
            try
            {
                for(int i = 0; i < 8; i++)
                {
                    java.awt.Toolkit.getDefaultToolkit().beep();
                    TimeUnit.MILLISECONDS.sleep(150);
                }
            }
            catch (InterruptedException ex)
            {
            }
        }

    }

}
